[package]
name = "horizon_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
tokio.workspace = true
config.workspace = true
color-eyre.workspace = true
lazy_static.workspace = true
directories.workspace = true

horizon_common = { path = "../horizon_common" }
