[package]
name = "horizon_registry"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }

[build-dependencies]
tonic-build = { version = "0.12.3", features = ["prost"] }
